kind: Deployment
apiVersion: apps/v1
metadata:
  name: hipster-frontend
spec:
  template:
    spec:
      serviceAccountName: APP_NAME-ksa
      containers:
      - name: server
        env:
        - name: ENVIRONMENT
          value: stg
