apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner-config-acm
  annotations:
    configmanagement.gke.io/cluster-selector: prod-us-central1
data:
  CI_SERVER_URL: https://GITLAB_HOSTNAME
  CLONE_URL: ""
  KUBERNETES_CPU_LIMIT: ""
  KUBERNETES_CPU_REQUEST: ""
  KUBERNETES_HELPER_CPU_LIMIT: ""
  KUBERNETES_HELPER_CPU_REQUEST: ""
  KUBERNETES_HELPER_IMAGE: ""
  KUBERNETES_HELPER_MEMORY_LIMIT: ""
  KUBERNETES_HELPER_MEMORY_REQUEST: ""
  KUBERNETES_IMAGE: ubuntu:16.04
  KUBERNETES_MEMORY_LIMIT: ""
  KUBERNETES_MEMORY_REQUEST: ""
  KUBERNETES_NAMESPACE: acm-tests
  KUBERNETES_PULL_POLICY: ""
  KUBERNETES_SERVICE_ACCOUNT: ""
  KUBERNETES_SERVICE_CPU_LIMIT: ""
  KUBERNETES_SERVICE_CPU_REQUEST: ""
  KUBERNETES_SERVICE_MEMORY_LIMIT: ""
  KUBERNETES_SERVICE_MEMORY_REQUEST: ""
  REGISTER_LOCKED: "true"
  RUNNER_EXECUTOR: kubernetes
  RUNNER_REQUEST_CONCURRENCY: "1"
  RUNNER_TAG_LIST: app:acm-tests, cluster:prod-us-central1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner-config-acm
  annotations:
    configmanagement.gke.io/cluster-selector: prod-us-east1
data:
  CI_SERVER_URL: https://GITLAB_HOSTNAME
  CLONE_URL: ""
  KUBERNETES_CPU_LIMIT: ""
  KUBERNETES_CPU_REQUEST: ""
  KUBERNETES_HELPER_CPU_LIMIT: ""
  KUBERNETES_HELPER_CPU_REQUEST: ""
  KUBERNETES_HELPER_IMAGE: ""
  KUBERNETES_HELPER_MEMORY_LIMIT: ""
  KUBERNETES_HELPER_MEMORY_REQUEST: ""
  KUBERNETES_IMAGE: ubuntu:16.04
  KUBERNETES_MEMORY_LIMIT: ""
  KUBERNETES_MEMORY_REQUEST: ""
  KUBERNETES_NAMESPACE: acm-tests
  KUBERNETES_PULL_POLICY: ""
  KUBERNETES_SERVICE_ACCOUNT: ""
  KUBERNETES_SERVICE_CPU_LIMIT: ""
  KUBERNETES_SERVICE_CPU_REQUEST: ""
  KUBERNETES_SERVICE_MEMORY_LIMIT: ""
  KUBERNETES_SERVICE_MEMORY_REQUEST: ""
  REGISTER_LOCKED: "true"
  RUNNER_EXECUTOR: kubernetes
  RUNNER_REQUEST_CONCURRENCY: "1"
  RUNNER_TAG_LIST: app:acm-tests, cluster:prod-us-east1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner-config-acm
  annotations:
    configmanagement.gke.io/cluster-selector: staging-us-central1
data:
  CI_SERVER_URL: https://GITLAB_HOSTNAME
  CLONE_URL: ""
  KUBERNETES_CPU_LIMIT: ""
  KUBERNETES_CPU_REQUEST: ""
  KUBERNETES_HELPER_CPU_LIMIT: ""
  KUBERNETES_HELPER_CPU_REQUEST: ""
  KUBERNETES_HELPER_IMAGE: ""
  KUBERNETES_HELPER_MEMORY_LIMIT: ""
  KUBERNETES_HELPER_MEMORY_REQUEST: ""
  KUBERNETES_IMAGE: ubuntu:16.04
  KUBERNETES_MEMORY_LIMIT: ""
  KUBERNETES_MEMORY_REQUEST: ""
  KUBERNETES_NAMESPACE: acm-tests
  KUBERNETES_PULL_POLICY: ""
  KUBERNETES_SERVICE_ACCOUNT: ""
  KUBERNETES_SERVICE_CPU_LIMIT: ""
  KUBERNETES_SERVICE_CPU_REQUEST: ""
  KUBERNETES_SERVICE_MEMORY_LIMIT: ""
  KUBERNETES_SERVICE_MEMORY_REQUEST: ""
  REGISTER_LOCKED: "true"
  RUNNER_EXECUTOR: kubernetes
  RUNNER_REQUEST_CONCURRENCY: "1"
  RUNNER_TAG_LIST: app:acm-tests, cluster:staging-us-central1
