---
# Source: gitlab-runner/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "release-name-gitlab-runner"
  labels:
    app: gitlab-runner
type: Opaque
data:
  runner-registration-token: "cHBMWl9teVJqakVHUDFRYjRDVXkK"
