kind: Deployment
apiVersion: apps/v1
metadata:
  name: shippingservice
spec:
  template:
    spec:
      containers:
      - name: server
        env:
        - name: ENVIRONMENT
          value: prod