---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitlab-runner-acm
rules:
- apiGroups:
  - "configmanagement.gke.io"
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
- apiGroups: [""]
  resources: ["pods", "pods/exec", "secrets"]
  verbs: ["get", "list", "watch", "create", "patch", "delete"]
- apiGroups:
  - ""
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-runner-acm
subjects:
- kind: ServiceAccount
  name: default
  namespace: acm-tests
roleRef:
  kind: ClusterRole
  name: gitlab-runner-acm
  apiGroup: rbac.authorization.k8s.io