# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

timeout: 7200s # 2hr
tags:
  - modern-cicd-anthos
substitutions:
  _DOMAIN: ""
  _BUILD_IMAGES: "true"
  _INSTALL_APPS: "true"
options:
  substitution_option: 'ALLOW_LOOSE'
steps:
- name: 'gcr.io/cloud-builders/gsutil'
  id: 'create-tf-state-bucket'
  entrypoint: 'bash'
  args:
  - '-xe'
  - '-c'
  - |
    gsutil mb gs://${PROJECT_ID}-anthos-platform-tf-state || true

- name: 'gcr.io/cloud-builders/gsutil'
  id: 'starter-repo-reference'
  entrypoint: 'bash'
  args:
  - '-xe'
  - '-c'
  - |
    gsutil mb gs://${PROJECT_ID}-starter-repos || true
    gsutil cp -r starter-repos gs://${PROJECT_ID}-starter-repos # TODO: use -m?

# Create build-installation-image
- name: "gcr.io/cloud-builders/gcloud"
  id: "build-install-image"
  entrypoint: bash
  args:
    - -c
    - |
      [[ "${_BUILD_IMAGES}" == "false" ]] && exit 0
      gcloud builds submit --config=build-image/cloudbuild.yaml

# - name: "gcr.io/cloud-builders/gcloud"
#   id: cleanup-sub-jobs
#   entrypoint: bash
#   args:
#     - -c
#     - |
#       gcloud builds list --ongoing --filter='tags[]~modern-cicd-anthos' --format='value(id)' | \
#         xargs --no-run-if-empty gcloud builds cancel

# Foundation
- name: "gcr.io/cloud-builders/gcloud"
  id: "trigger-foundation"
  dir: "0_foundation"
  entrypoint: bash
  args:
    - -c
    - |
      gcloud builds submit
  waitFor:
    - build-install-image

# Clusters
- name: "gcr.io/cloud-builders/gcloud"
  id: "trigger-clusters"
  dir: "1_clusters"
  entrypoint: bash
  args:
    - -c
    - |
      gcloud builds submit
  waitFor:
    - trigger-foundation

# CICD
- name: "gcr.io/cloud-builders/gcloud"
  id: "trigger-gitlab"
  dir: "2_gitlab"
  entrypoint: bash
  args:
    - -c
    - |
      gcloud builds submit --substitutions=_DOMAIN=${_DOMAIN}
  waitFor:
    - trigger-clusters

# ACM

- name: "gcr.io/cloud-builders/gcloud"
  id: "trigger-acm-install"
  dir: "3_acm"
  entrypoint: bash
  args:
    - -c
    - |
      gcloud builds submit --substitutions=_DOMAIN=${_DOMAIN}
  waitFor:
    - trigger-gitlab

# Apps
- name: "gcr.io/cloud-builders/gcloud"
  id: "trigger-app-install"
  dir: "4_demo"
  entrypoint: bash
  args:
    - -c
    - |
      [[ "${_INSTALL_APPS}" == "false" ]] && exit 0
      gcloud builds submit --substitutions=_DOMAIN=${_DOMAIN}
  waitFor:
    - trigger-acm-install

- name: 'gcr.io/${PROJECT_ID}/anthos-platform-installer'
  id: "output-connect-details"
  entrypoint: bash
  args:
    - -c
    - |
      export GITLAB_PASSWORD=$(gcloud secrets versions access latest --secret="gitlab-password")
      export GITLAB_HOSTNAME="gitlab.${_DOMAIN}"

      echo "Log in to your GitLab instance at: https://$${GITLAB_HOSTNAME}"
      echo "Username: root"
      echo "Password: $${GITLAB_PASSWORD}"
      echo ""
      echo "Retrieve password: $(gcloud secrets versions access latest --secret=\"gitlab-password\")"
      echo "true"
      echo "Visit the user guide in the docs (docs/index.md) to go through a user journey (add, deploy, and change applications)."
  waitFor:
    - trigger-app-install