# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Customize the namespace to be the namespace name used for prod-east environment.
# This change should be made before `appcel env add prod-east`.
# Once the prod-east environment is added, the namespace shouldn't be changed.
namespace: prod-east

resources:
- ../../base/app
- ../../base/redis

# update the image in this patch.
patches:
- deployment.yaml

configmapGenerator:
- name: redishost
  literals:
  - REDISHOST=redis-master.$(NAMESPACE).svc.cluster.local

vars:
- name: NAMESPACE
  objref:
    kind: Service
    name: redis-master
    apiVersion: v1
  fieldref:
    fieldpath: metadata.namespace

configurations:
- varReference.yaml

# To use a different redis host available at <HOST> with the password <PASSWORD>,
# make the following change in the current kustomization.yaml.
#
# 1. remove - ../../base/redis from the resources. The resources will be
#    resources:
#    - ../../base.app
#
# 2. change the configmapGenerator to use <HOST>. The configmapGenerator will be
# configmapGenerator:
# - name: redishost
#   literals:
#    - REDISHOST=<HOST>
#
# 3. uncomment the following secretGenerator:
# secretGenerator:
# - name: redis
#   literals:
#   - redis-password=<PASSWORD>

