apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner-config
  annotations:
    configmanagement.gke.io/cluster-selector: prod-east
data:
  CI_SERVER_URL: "https://gitlab.platform.1.vic.dev/"
  CLONE_URL: ""
  RUNNER_REQUEST_CONCURRENCY: "1"
  RUNNER_EXECUTOR: "kubernetes"
  REGISTER_LOCKED: "true"
  RUNNER_TAG_LIST: "app:APP_NAME, cluster:prod-east"
  KUBERNETES_IMAGE: "ubuntu:16.04"
  KUBERNETES_NAMESPACE: "APP_NAME"
  KUBERNETES_CPU_LIMIT: ""
  KUBERNETES_MEMORY_LIMIT: ""
  KUBERNETES_CPU_REQUEST: ""
  KUBERNETES_MEMORY_REQUEST: ""
  KUBERNETES_SERVICE_ACCOUNT: ""
  KUBERNETES_SERVICE_CPU_LIMIT: ""
  KUBERNETES_SERVICE_MEMORY_LIMIT: ""
  KUBERNETES_SERVICE_CPU_REQUEST: ""
  KUBERNETES_SERVICE_MEMORY_REQUEST: ""
  KUBERNETES_HELPER_CPU_LIMIT: ""
  KUBERNETES_HELPER_MEMORY_LIMIT: ""
  KUBERNETES_HELPER_CPU_REQUEST: ""
  KUBERNETES_HELPER_MEMORY_REQUEST: ""
  KUBERNETES_HELPER_IMAGE: ""
  KUBERNETES_PULL_POLICY: "always"
