kind: Deployment
apiVersion: apps/v1
metadata:
  name: app
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: APP_NAME-ksa
      containers:
      - name: app
        env:
        - name: ENVIRONMENT
          value: stg
