apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: app-template
build:
  artifacts:
  # Make sure the skaffold "default-repo" is set.
  # Follow the doc for instructions https://github.com/GoogleCloudPlatform/solutions-modern-cicd-anthos/blob/master/docs/index.md#testing-the-change-locally-with-skaffold 
  - image: app
profiles:
  - name: staging-central
    deploy:
      kubectl:
        manifests:
        - config/envs/staging-central/deployment.yaml
        flags:
          disableValidation: true
  - name: prod-central
    deploy:
      kubectl:
        manifests:
        - config/envs/prod-central/deployment.yaml
        flags:
          disableValidation: true
  - name: prod-east
    deploy:
      kubectl:
        manifests:
        - config/envs/prod-east/deployment.yaml
        flags:
          disableValidation: true
