apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: app-template
profiles:
  # Profile used when building images in CI
  - name: ci
    build:
      cluster:
        dockerConfig:
          path: ~/.docker/config.json          
  # Profile to render "staging-west" manifest.
  # It is only aimed to add the image digest but not generates the fully
  # hydrated config. So the `--validate` flag of kubectl should be
  # disabled (disableValidation=true) and should not use kustomize deployer.
  - name: staging-west
    deploy:
      kubectl:
        manifests:
        - config/envs/staging-west/deployment.yaml
        flags:
          disableValidation: true
  # Profile to render "prod-central" manifest.
  # It is only aimed to add the image digest but not generates the fully
  # hydrated config. So the `--validate` flag of kubectl should be
  # disabled (disableValidation=true) and should not use kustomize deployer.
  - name: prod-central
    deploy:
      kubectl:
        manifests:
        - config/envs/prod-central/deployment.yaml
        flags:
          disableValidation: true
  # Profile to render "prod-east" manifest.
  # It is only aimed to add the image digest but not generates the fully
  # hydrated config. So the `--validate` flag of kubectl should be
  # disabled (disableValidation=true) and should not use kustomize deployer.
  - name: prod-east
    deploy:
      kubectl:
        manifests:
        - config/envs/prod-east/deployment.yaml
        flags:
          disableValidation: true