apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    cnrm.gitlab.com/version: 0.0.0-dev
  creationTimestamp: null
  labels:
    cnrm.gitlab.com/managed-by-kcc: "true"
    cnrm.gitlab.com/system: "true"
    cnrm.gitlab.com/tf2crd: "true"
  name: projects.cnrm.gitlab.com
spec:
  group: cnrm.gitlab.com
  names:
    categories:
    - saas
    kind: Project
    plural: projects
    shortNames:
    - gitproject
    - gitprojects
    singular: project
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'apiVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            approvalsBeforeMerge:
              type: integer
            archived:
              description: Whether the project is archived.
              type: boolean
            containerRegistryEnabled:
              type: boolean
            defaultBranch:
              type: string
            description:
              type: string
            groupRef:
              oneOf:
              - not:
                  required:
                  - external
                required:
                - name
              - not:
                  anyOf:
                  - required:
                    - name
                  - required:
                    - namespace
                required:
                - external
              properties:
                external:
                  description: The groupId of a Group.
                  type: string
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
                  type: string
                namespace:
                  description: 'Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/'
                  type: string
              type: object
            initializeWithReadme:
              type: boolean
            issuesEnabled:
              type: boolean
            lfsEnabled:
              type: boolean
            mergeMethod:
              type: string
            mergeRequestsEnabled:
              type: boolean
            onlyAllowMergeIfAllDiscussionsAreResolved:
              type: boolean
            onlyAllowMergeIfPipelineSucceeds:
              type: boolean
            path:
              type: string
            pipelinesEnabled:
              type: boolean
            removeSourceBranchAfterMerge:
              type: boolean
            requestAccessEnabled:
              type: boolean
            sharedRunnersEnabled:
              type: boolean
            sharedWithGroups:
              items:
                properties:
                  groupAccessLevel:
                    type: string
                  groupId:
                    type: integer
                  groupName:
                    type: string
                required:
                - groupAccessLevel
                - groupId
                type: object
              type: array
            snippetsEnabled:
              type: boolean
            tags:
              items:
                type: string
              type: array
            visibilityLevel:
              type: string
            wikiEnabled:
              type: boolean
          type: object
        status:
          properties:
            conditions:
              description: Conditions represents the latest available observation
                of the resource's current state.
              items:
                properties:
                  lastTransitionTime:
                    description: Last time the condition transitioned from one status
                      to another.
                    type: string
                  message:
                    description: Human-readable message indicating details about last
                      transition.
                    type: string
                  reason:
                    description: Unique, one-word, CamelCase reason for the condition's
                      last transition.
                    type: string
                  status:
                    description: Status is the status of the condition. Can be True,
                      False, Unknown.
                    type: string
                  type:
                    description: Type is the type of the condition.
                    type: string
                type: object
              type: array
            httpUrlToRepo:
              type: string
            projectId:
              type: string
            runnersToken:
              type: string
            sshUrlToRepo:
              type: string
            webUrl:
              type: string
          type: object
      type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
