apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    cnrm.gitlab.com/version: 0.0.0-dev
  creationTimestamp: null
  labels:
    cnrm.gitlab.com/managed-by-kcc: "true"
    cnrm.gitlab.com/system: "true"
    cnrm.gitlab.com/tf2crd: "true"
  name: groups.cnrm.gitlab.com
spec:
  group: cnrm.gitlab.com
  names:
    categories:
    - saas
    kind: Group
    plural: groups
    shortNames:
    - gitgroup
    - gitgroups
    singular: group
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'apiVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            description:
              type: string
            lfsEnabled:
              type: boolean
            parentId:
              type: integer
            path:
              type: string
            requestAccessEnabled:
              type: boolean
            visibilityLevel:
              type: string
          required:
          - path
          type: object
        status:
          properties:
            conditions:
              description: Conditions represents the latest available observation
                of the resource's current state.
              items:
                properties:
                  lastTransitionTime:
                    description: Last time the condition transitioned from one status
                      to another.
                    type: string
                  message:
                    description: Human-readable message indicating details about last
                      transition.
                    type: string
                  reason:
                    description: Unique, one-word, CamelCase reason for the condition's
                      last transition.
                    type: string
                  status:
                    description: Status is the status of the condition. Can be True,
                      False, Unknown.
                    type: string
                  type:
                    description: Type is the type of the condition.
                    type: string
                type: object
              type: array
            fullName:
              type: string
            fullPath:
              type: string
            groupId:
              type: string
            runnersToken:
              type: string
            webUrl:
              type: string
          type: object
      required:
      - spec
      type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
