apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  name: gitlab
  annotations:
    cnrm.cloud.google.com/remove-default-node-pool: "true" # don't create the default node pool
  namespace: gitlab # {"$kpt-set":"namespace"}
spec:
  location: us-central1
  initialNodeCount: 1 # this field must be set to greater than 0
  networkRef:
    name: gitlab
  subnetworkRef:
    name: gitlab
  ipAllocationPolicy:
    clusterSecondaryRangeName: gitlab-cluster-pod-cidr
    servicesSecondaryRangeName: gitlab-cluster-service-cidr
  masterAuth:
    clientCertificateConfig:
      issueClientCertificate: true
---
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  name: gitlab
  namespace: gitlab # {"$kpt-set":"namespace"}
spec:
  clusterRef:
    name: gitlab
  nodeCount: 1
  location: us-central1
  nodeConfig:
    labels:
      cluster_name: gitlab
    machineType: n1-standard-4
    metadata:
      cluster_name: gitlab
    serviceAccountRef:
      name: gitlab-cluster
    oauthScopes:
    - "https://www.googleapis.com/auth/compute"
    - "https://www.googleapis.com/auth/devstorage.read_only"
    - "https://www.googleapis.com/auth/logging.write"
    - "https://www.googleapis.com/auth/monitoring"
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: gitlab-cluster
  namespace: gitlab # {"$kpt-set":"namespace"}
spec:
  displayName: Service Account for GitLab cluster
