apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  name: anthos-platform
  namespace: YOUR_NAMESPACE # {"$kpt-set":"namespace"}
spec:
  autoCreateSubnetworks: false
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: anthos-platform-central
  namespace: YOUR_NAMESPACE # {"$kpt-set":"namespace"}
spec:
  ipCidrRange: 10.2.0.0/16
  region: us-central1
  secondaryIpRange:
  - ipCidrRange: 172.16.0.0/16
    rangeName: anthos-platform-pods-prod
  - ipCidrRange: 172.17.0.0/16
    rangeName: anthos-platform-pods-staging
  - ipCidrRange: 172.18.0.0/16
    rangeName: anthos-platform-pods-dev
  - ipCidrRange: 192.168.0.0/24
    rangeName: anthos-platform-services-prod
  - ipCidrRange: 192.168.1.0/24
    rangeName: anthos-platform-services-staging
  - ipCidrRange: 192.168.2.0/24
    rangeName: anthos-platform-services-dev
  networkRef:
    name: anthos-platform
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: anthos-platform-east
  namespace: YOUR_NAMESPACE # {"$kpt-set":"namespace"}
spec:
  ipCidrRange: 10.3.0.0/16
  region: us-east1
  secondaryIpRange:
  - ipCidrRange: 172.19.0.0/16
    rangeName: anthos-platform-pods-prod
  - ipCidrRange: 192.168.3.0/24
    rangeName: anthos-platform-services-prod
  networkRef:
    name: anthos-platform
