apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
      - name: app
        image: app
        env:
        # Required for Skaffold to detect runtime language
        # https://skaffold.dev/docs/workflows/debug/#go
        - name: GOTRACEBACK
          value: single
        - name: ENVIRONMENT
          value: dev
