Vet staging:
  image: viglesiasce/anthos-config-management:v1.0.0-rc.45
  tags:
  - app:acm-tests
  - cluster:staging
  variables:
    USER: root
    KUBECONFIG: kubeconfig
  script:
  - sh generate_config.sh
  - nomos version
  #- nomos status
  - nomos vet

Vet prod-central:
  image: viglesiasce/anthos-config-management:v1.0.0-rc.45
  tags:
  - app:acm-tests
  - cluster:prod-central
  variables:
    USER: root
    KUBECONFIG: kubeconfig
  script:
  - sh generate_config.sh
  - nomos version
  #- nomos status
  - nomos vet

Vet prod-east:
  image: viglesiasce/anthos-config-management:v1.0.0-rc.45
  tags:
  - app:acm-tests
  - cluster:prod-east
  variables:
    USER: root
    KUBECONFIG: kubeconfig
  script:
  - sh generate_config.sh
  - nomos version
  #- nomos status
  - nomos vet
