Vet staging-us-central1:
  image: gcr.io/config-management-release/nomos:v1.2.0-rc.11
  tags:
  - app:acm-tests
  - cluster:staging-us-central1
  variables:
    USER: root
    KUBECONFIG: kubeconfig
  script:
  - sh generate_config.sh
  - nomos version
  - nomos status
  - nomos vet

Vet prod-us-central1:
  image: gcr.io/config-management-release/nomos:v1.2.0-rc.11
  tags:
  - app:acm-tests
  - cluster:prod-us-central1
  variables:
    USER: root
    KUBECONFIG: kubeconfig
  script:
  - sh generate_config.sh
  - nomos version
  - nomos status
  - nomos vet

Vet prod-us-east1:
  image: gcr.io/config-management-release/nomos:v1.2.0-rc.11
  tags:
  - app:acm-tests
  - cluster:prod-us-east1
  variables:
    USER: root
    KUBECONFIG: kubeconfig
  script:
  - sh generate_config.sh
  - nomos version
  - nomos status
  - nomos vet
