Vet staging:
  image: gcr.io/config-management-release/nomos:v1.2.0-rc.11
  tags:
  - app:acm-tests
  - cluster:staging
  variables:
    USER: root
    KUBECONFIG: kubeconfig
  script:
  - sh generate_config.sh
  - nomos version
  - nomos status
  - nomos vet

Vet prod-central:
  image: gcr.io/config-management-release/nomos:v1.2.0-rc.11
  tags:
  - app:acm-tests
  - cluster:prod-central
  variables:
    USER: root
    KUBECONFIG: kubeconfig
  script:
  - sh generate_config.sh
  - nomos version
  - nomos status
  - nomos vet

Vet prod-east:
  image: gcr.io/config-management-release/nomos:v1.2.0-rc.11
  tags:
  - app:acm-tests
  - cluster:prod-east
  variables:
    USER: root
    KUBECONFIG: kubeconfig
  script:
  - sh generate_config.sh
  - nomos version
  - nomos status
  - nomos vet
