apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner-config-acm
  annotations:
    configmanagement.gke.io/cluster-selector: staging
data:
  CI_SERVER_URL: https://gitlab.platform.1.vic.dev/
  CLONE_URL: ""
  KUBERNETES_CPU_LIMIT: ""
  KUBERNETES_CPU_REQUEST: ""
  KUBERNETES_HELPER_CPU_LIMIT: ""
  KUBERNETES_HELPER_CPU_REQUEST: ""
  KUBERNETES_HELPER_IMAGE: ""
  KUBERNETES_HELPER_MEMORY_LIMIT: ""
  KUBERNETES_HELPER_MEMORY_REQUEST: ""
  KUBERNETES_IMAGE: ubuntu:16.04
  KUBERNETES_MEMORY_LIMIT: ""
  KUBERNETES_MEMORY_REQUEST: ""
  KUBERNETES_NAMESPACE: acm-tests
  KUBERNETES_PULL_POLICY: ""
  KUBERNETES_SERVICE_ACCOUNT: ""
  KUBERNETES_SERVICE_CPU_LIMIT: ""
  KUBERNETES_SERVICE_CPU_REQUEST: ""
  KUBERNETES_SERVICE_MEMORY_LIMIT: ""
  KUBERNETES_SERVICE_MEMORY_REQUEST: ""
  REGISTER_LOCKED: "true"
  RUNNER_EXECUTOR: kubernetes
  RUNNER_REQUEST_CONCURRENCY: "1"
  RUNNER_TAG_LIST: acm-tests, staging
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner-config-acm
  annotations:
    configmanagement.gke.io/cluster-selector: prod-east
data:
  CI_SERVER_URL: https://gitlab.platform.1.vic.dev/
  CLONE_URL: ""
  KUBERNETES_CPU_LIMIT: ""
  KUBERNETES_CPU_REQUEST: ""
  KUBERNETES_HELPER_CPU_LIMIT: ""
  KUBERNETES_HELPER_CPU_REQUEST: ""
  KUBERNETES_HELPER_IMAGE: ""
  KUBERNETES_HELPER_MEMORY_LIMIT: ""
  KUBERNETES_HELPER_MEMORY_REQUEST: ""
  KUBERNETES_IMAGE: ubuntu:16.04
  KUBERNETES_MEMORY_LIMIT: ""
  KUBERNETES_MEMORY_REQUEST: ""
  KUBERNETES_NAMESPACE: acm-tests
  KUBERNETES_PULL_POLICY: ""
  KUBERNETES_SERVICE_ACCOUNT: ""
  KUBERNETES_SERVICE_CPU_LIMIT: ""
  KUBERNETES_SERVICE_CPU_REQUEST: ""
  KUBERNETES_SERVICE_MEMORY_LIMIT: ""
  KUBERNETES_SERVICE_MEMORY_REQUEST: ""
  REGISTER_LOCKED: "true"
  RUNNER_EXECUTOR: kubernetes
  RUNNER_REQUEST_CONCURRENCY: "1"
  RUNNER_TAG_LIST: acm-tests, prod-east
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner-config-acm
  annotations:
    configmanagement.gke.io/cluster-selector: prod-central
data:
  CI_SERVER_URL: https://gitlab.platform.1.vic.dev/
  CLONE_URL: ""
  KUBERNETES_CPU_LIMIT: ""
  KUBERNETES_CPU_REQUEST: ""
  KUBERNETES_HELPER_CPU_LIMIT: ""
  KUBERNETES_HELPER_CPU_REQUEST: ""
  KUBERNETES_HELPER_IMAGE: ""
  KUBERNETES_HELPER_MEMORY_LIMIT: ""
  KUBERNETES_HELPER_MEMORY_REQUEST: ""
  KUBERNETES_IMAGE: ubuntu:16.04
  KUBERNETES_MEMORY_LIMIT: ""
  KUBERNETES_MEMORY_REQUEST: ""
  KUBERNETES_NAMESPACE: acm-tests
  KUBERNETES_PULL_POLICY: ""
  KUBERNETES_SERVICE_ACCOUNT: ""
  KUBERNETES_SERVICE_CPU_LIMIT: ""
  KUBERNETES_SERVICE_CPU_REQUEST: ""
  KUBERNETES_SERVICE_MEMORY_LIMIT: ""
  KUBERNETES_SERVICE_MEMORY_REQUEST: ""
  REGISTER_LOCKED: "true"
  RUNNER_EXECUTOR: kubernetes
  RUNNER_REQUEST_CONCURRENCY: "1"
  RUNNER_TAG_LIST: acm-tests, prod-central