apiVersion: apps/v1
kind: Deployment
metadata:
  name: petabank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petabank
  template:
    metadata:
      labels:
        app: petabank
    spec:
      containers:
      - name: server
        image: app
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          value: base
        - name: PORT
          value: "8080"
