apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
      - name: app
        # Please change the image to your own container registry address.
        # "image" has to be placed in each individual deployment.yaml 
        # rather than in the ../base/app/deployment.yaml. This allows 
        # the skaffold kubectl deployer to attach the image digest
        image: app
        env:
        - name: ENVIRONMENT
          value: staging-cental
