# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

timeout: 3600s # 1-hr
tags:
  - modern-cicd-anthos
  - gitlab
substitutions:
  _BUILD_IMAGES: "true"
  _CREATE_GITLAB: "true"
  _DESTROY_CLUSTER: "true"
  _DESTROY_REPOS: "true"
  _PROJECT_ID: ${PROJECT_ID}
options:
  substitution_option: 'ALLOW_LOOSE'
steps:
# Uninstall gitlab additions
- name: 'gcr.io/${_PROJECT_ID}/anthos-platform-installer'
  id: 'destroy-gitlab-install'
  entrypoint: 'bash'
  args:
  - '-xe'
  - '-c'
  - |
    [[ "${_DESTROY_REPOS}" == "false" ]] && exit 0
    sed -i "s/YOUR_PROJECT_ID/${_PROJECT_ID}/g" terraform.tfvars
    sed -i "s/YOUR_PROJECT_ID/${_PROJECT_ID}/g" backend.tf
    sed -i "s/YOUR_PROJECT_ID/${_PROJECT_ID}/g" gitlab-repos/backend.tf

    pushd gitlab-repos

    terraform init
    export GITLAB_PASSWORD=$(gcloud secrets versions access latest --secret="gitlab-password --project=${_PROJECT_ID}")

    [[ -z "$${GITLAB_PASSWORD}" ]] && exit 0 # No need to continue if no password
    terraform destroy -auto-approve -var gitlab_token=$${GITLAB_PASSWORD}

    # remove private keys stored in secrets manager
    gcloud secrets delete "gitlab-cluster-key-$${CLUSTER}" --quiet --project=${_PROJECT_ID} || true

    popd

# Cluster destroy
- name: 'gcr.io/${_PROJECT_ID}/anthos-platform-installer'
  id: 'destroy-gitlab-cluster'
  entrypoint: 'bash'
  args:
  - '-xe'
  - '-c'
  - |
    [[ "${_DESTROY_CLUSTER}" == "false" ]] && exit 0
    sed -i "s/YOUR_PROJECT_ID/${_PROJECT_ID}/g" terraform.tfvars
    sed -i "s/YOUR_PROJECT_ID/${_PROJECT_ID}/g" backend.tf
    sed -i "s/YOUR_PROJECT_ID/${_PROJECT_ID}/g" gitlab-repos/backend.tf

    # TODO Manually empty bucket contents as otherwise gke-gitlab cannot delete them pending:
    # https://github.com/terraform-google-modules/terraform-google-gke-gitlab/issues/49
    gsutil rm "gs://${_PROJECT_ID}-gitlab-artifacts/**" || true
    gsutil rm "gs://${_PROJECT_ID}-registry/**" || true
    gsutil rm "gs://${_PROJECT_ID}-runner-cache/**" || true

    terraform init
    terraform destroy -auto-approve
  waitFor:
    - destroy-gitlab-install

# Cluster Secrets
- name: 'gcr.io/${_PROJECT_ID}/anthos-platform-installer'
  id: 'destroy-gitlab-secrets'
  entrypoint: 'bash'
  args:
  - '-xe'
  - '-c'
  - |
    [[ "${_DESTROY_CLUSTER}" == "true" ]] && exit 0
    gcloud secrets delete gitlab-user --quiet || true
    gcloud secrets delete gitlab-password --quiet || true
  waitFor:
    - destroy-gitlab-install
    - destroy-gitlab-cluster
